# -*- coding: utf-8 -*-
"""DatasetOverview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JATdsFkBHiLCn2lUMCkoeuMgGXjYLhIC
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("CryptoData.csv")

data.head(10)

data.tail(5)

data.info()

data.shape

data.describe()

data.columns

data.dtypes