# -*- coding: utf-8 -*-
"""DatasetOverview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JATdsFkBHiLCn2lUMCkoeuMgGXjYLhIC
"""

import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("CryptoData.csv")

data.head()

data.tail(5)

missing_vales = data.isnull().sum()
print("Missing Values")
print(missing_vales)

data.dropna(inplace=True)

duplicate_rows = data[data.duplicated()]
print("Duplicate Rows")
print(duplicate_rows)

data.drop_duplicates(inplace=True)

def handle_outliers(column,z_threshold=3):
  z_scores = np.abs((column - column.mean())/column.std())
  filtered_data = column[z_scores < z_threshold]
  return filtered_data

handleoutlier = data.copy()
handleoutlier["close"] = handle_outliers(handleoutlier["close"])

outliers = data[~data.index.isin(handleoutlier.index)]
print("Outliers")
print(outliers)