# -*- coding: utf-8 -*-
"""Analyzing&VisualizingVolatility.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NylI510R090vHRJQBU2f6qQzgWjty_y6
"""

import pandas as pd
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()

data = pd.read_csv("CryptoData.csv")

data.head()

data["Daily_Returns"] = data["close"].pct_change()

daily_volatility = data["Daily_Returns"].std()

data["Year"] = pd.to_datetime(data["date"]).dt.year

annual_volatility = data.groupby("Year")["Daily_Returns"].std()

print("Daily Volatility:", daily_volatility)
print("Annual Volatility", annual_volatility)

plt.figure(figsize=(10,6))
annual_volatility.plot(kind="bar",color="blue")
plt.title("Annual Volatility of XRP-USDT")
plt.xlabel("Year")
plt.ylabel("Volatility")
plt.show()