# -*- coding: utf-8 -*-
"""Detecting Trend with Moving Average.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pwaPiHlo5qVTQNyhGQYzM4bROyv9KQZb
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("CryptoData.csv")

data.head()

data["date"] = pd.to_datetime(data["date"])

data.set_index("date", inplace=True)

# Calculate 7 Days moving average
data["Moving_avg"] = data["close"].rolling(window=7).mean()

plt.figure(figsize=(10,6))
plt.plot(data.index, data["close"],label="Original Close Price",color="blue")
plt.plot(data.index, data["Moving_avg"],label="7 Days moving average",color="green")
plt.title("Trend Detection: 7 Days Moving Average")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.show()