# -*- coding: utf-8 -*-
"""ForecastingwithTimeSeriesDecomposition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16oLmhXaZWMd42mTVqTAfAGZp35vicAVC
"""

import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.seasonal import STL

uploaded = files.upload()

data = pd.read_csv("CryptoData.csv")

data.head()

data["date"] = pd.to_datetime(data["date"])

prices = data["close"]

stl = STL(prices,period=60,seasonal=7)
result = stl.fit()

seasonal = result.seasonal
trend = result.trend
reisdual = result.resid

# Forecast price for the next 5 days
last_date = data["date"].iloc[-1]
forecast_date = pd.date_range(start=last_date, periods=5, freq="D")
forecasted_prices = trend + seasonal + reisdual

print("Forecasted prices for the next 5 days")
for date, price in zip(forecast_date, forecasted_prices):
  print(f"{date.date()}:{price:.2f}")