# -*- coding: utf-8 -*-
"""FindingCorrelationBetweenPrice&Volume.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zu2oipUbDxiKnlQcWXBPrEiJ0qmVgcR4
"""

import pandas as pd
import numpy as np
from google.colab import files
import tensorflow as tf

uploaded = files.upload()

data = pd.read_csv("CryptoData.csv")

data.head()

features = data["Volume XRP"]
target = data["close"]

model = tf.keras.Sequential([tf.keras.layers.Dense(1,input_shape=(1,))])
model.compile(optimizer='sgd',loss="mean_squared_error")

# Train the model
model.fit(features,target, epochs=100,verbose=0)

correlation = np.corrcoef(features,target)[0,1]
print(f"Correlation coefficient: {correlation:.2f}")